name: Bug report
description: Submit a bug report to help us improve
title: "[BUG] "
labels: ["C-bug", "S-awaiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit this bug report. Before submitting, please consider the following suggestions:
        1. Ensure that you are on the most recent version of the application.
        2. Please fill out the provided template as accurately and comprehensively as possible. Providing a clear bug report with a reproducible example enables us to address the issue more efficiently.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: It bugs out when ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you think should happen? Add request-response bodies, if applicable.
      placeholder: It should ...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What did actually happen? Add request-response bodies or screenshots, if applicable.
      placeholder: It actually ...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context For The Bug
      description: How has this issue affected you? What are you trying to accomplish?
      placeholder: Providing context (e.g. request-response bodies, stack trace or log data) helps us come up with a solution that is most useful in the real world.
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: Have you spent some time to check if this bug has been raised before?
      options:
        - label: I checked and didn't find similar issue
          required: true

  - type: dropdown
    id: willing-to-submit-pr
    attributes:
      label: Are you willing to submit a PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
