name: Feature request
description: Submit a proposal for a new feature
title: "[FEATURE] "
labels: ["C-feature", "S-awaiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        We appreciate the time and effort you have dedicated to submitting this feature request form. Before you proceed with submitting, kindly consider the following recommendations:
        1. Ensure that you are on the most recent version of the application.
        2. Please endeavor to complete the provided template to the best of your abilities. A well-defined and precise feature request allows us to expedite our work more efficiently.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature is.
      placeholder: In my use-case, ...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: A clear and concise description of what you want to happen.
      placeholder: Not obligatory, but ideas as to the implementation of the addition or change
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: Have you spent some time to check if this feature request has been raised before?
      options:
        - label: I checked and didn't find similar issue
          required: true

  - type: dropdown
    id: willing-to-submit-pr
    attributes:
      label: Are you willing to submit a PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
